In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# The path to our CSV file
csv = "csv_references/State_Characteristics.csv"

# Read our purchase data into pandas
Statesummaries_df = pd.read_csv(csv)
Statesummaries_df.head()

,Percent Uninsured,Percent of Medicare Enrollees with at Least One Primary Care Visit,Percent Black,Percent Hispanic,Mean Household Income,Median House Value,Percent College Grads
0,20.810048,68.396118,3.370547,4.117386,39316.127927,189058.544520,20.810048
1,17.025655,83.011464,25.861258,1.705156,33407.113797,113881.208651,17.025655
2,20.627987,80.983545,15.583714,3.249271,31613.757775,95801.433543,20.627987
3,19.313449,79.607123,2.922467,25.252582,37996.247733,159287.376412,19.313449
4,20.643943,72.221846,6.441747,32.376801,41101.182974,303544.618008,20.643943

In [ ]:
# Create a bar chart based off of the group series from before
# # x_axis = np.arange(statesummaries_df)
# # tick_locations = [value+0.4 for value in x_axis]

# plt.bar(x_axis, statesummaries_df["Percent Uninsured"], alpha=0.5, align="edge")
# plt.xticks(tick_locations, statesummaries_df["State Abbreviation"], rotation="vertical")

# plt.title("Percent Uninsured By State State")
# plt.xlabel("State")
# plt.ylabel("Percent Uninsured")

# plt.show()